[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8"
bytes = "1.2"
prost = "0.11"
prost-derive = "0.11"
prost-types = "0.11"
tokio = "1.20"
futures-preview = "0.2.2"
async-stream = "0.3.3"
http = "0.2.8"
tower = "0.4"
serde = "1"
serde_json = "1"
serde_derive = "1"
console = "0.15"

postgres = "0.19.4"
dotenv = "0.15.0"
chrono = "0.4.22"
uuid = { version = "1.1.2", features = ["serde", "v4"] }

[build-dependencies]
tonic-build = "0.8"


# [dependencies]
# tonic = { version = "0.1.0-alpha.4", features = ["rustls"] }
# bytes = "0.4"
# prost = "0.5"
# prost-derive = "0.5"
# prost-types = "0.5.0"
# tokio = "=0.2.0-alpha.6"
# futures-preview = { version = "=0.3.0-alpha.19", default-features = false, features = ["alloc"]}
# async-stream = "0.1.2"
# http = "0.1"
# tower = "=0.3.0-alpha.2"
# serde = "1.0.101"
# serde_json = "1.0.41"
# serde_derive = "1.0.101"
# console = "0.9.0"
# # Database(Postgresql)
# postgres = { version = "0.15.2", features = ["with-chrono"] }
# dotenv = "0.15.0"
# chrono = "0.4.9"
# uuid = { version = "0.8.1", features = ["serde", "v4"] }

# # Help you use gRPC protobuf files in Rust.
# [build-dependencies]
# tonic-build = "0.1.0-alpha.4"